steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/k8s-centos-phpfpm-nginx-lumen:$REVISION_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/k8s-centos-phpfpm-nginx-lumen:$REVISION_ID']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
        - 'set'
        - 'image'
        - 'deployments/k8s-lumen'
        - 'k8s-centos-phpfpm-nginx-lumen=gcr.io/$PROJECT_ID/k8s-centos-phpfpm-nginx-lumen:$REVISION_ID'
    env:
        - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b'
        - 'CLOUDSDK_CONTAINER_CLUSTER=rebate-cluster-dev'
