apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    annotations:
        deployment.kubernetes.io/revision: '13'
        kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"8"},"creationTimestamp":"2018-09-05T05:20:01Z","generation":11,"labels":{"app":"k8s-lumen"},"name":"k8s-lumen","namespace":"default","resourceVersion":"1895540","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/k8s-lumen","uid":"56a07e26-b0cb-11e8-b231-42010a9400c2"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"k8s-lumen"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"k8s-lumen"}},"spec":{"containers":[{"image":"gcr.io/rebatemango-dev/k8s-centos-phpfpm-nginx-lumen:06723594668379754a587b66f6210bfd69fb68f7","imagePullPolicy":"IfNotPresent","name":"k8s-centos-phpfpm-nginx-lumen","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2018-09-06T09:06:34Z","lastUpdateTime":"2018-09-06T09:06:34Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2018-09-05T05:20:01Z","lastUpdateTime":"2018-09-06T09:22:09Z","message":"ReplicaSet \"k8s-lumen-6684dc66f7\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":11,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    creationTimestamp: 2018-09-05T05:20:01Z
    generation: 26
    labels:
        app: k8s-lumen
    name: k8s-lumen
    namespace: default
    resourceVersion: '1990397'
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/k8s-lumen
    uid: 56a07e26-b0cb-11e8-b231-42010a9400c2
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: k8s-lumen
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: k8s-lumen
        spec:
            containers:
                - image: gcr.io/rebatemango-dev/k8s-centos-phpfpm-nginx-lumen:7ddb73d7a770d44e46ce6b841add6902ea17c175
                  imagePullPolicy: IfNotPresent
                  name: k8s-centos-phpfpm-nginx-lumen
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
status:
    availableReplicas: 1
    conditions:
        - lastTransitionTime: 2018-09-05T05:20:01Z
          lastUpdateTime: 2018-09-06T15:42:53Z
          message: ReplicaSet "k8s-lumen-6658554f75" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: 'True'
          type: Progressing
        - lastTransitionTime: 2018-09-07T04:23:20Z
          lastUpdateTime: 2018-09-07T04:23:20Z
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: 'True'
          type: Available
    observedGeneration: 26
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
