apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"7"},"creationTimestamp":"2018-09-05T05:20:01Z","generation":8,"labels":{"app":"k8s-lumen"},"name":"k8s-lumen","namespace":"default","resourceVersion":"1786349","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/k8s-lumen","uid":"56a07e26-b0cb-11e8-b231-42010a9400c2"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"k8s-lumen"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"k8s-lumen"}},"spec":{"containers":[{"image":"gcr.io/rebatemango-dev/k8s-centos-phpfpm-nginx-lumen:4a60ab2c6aaaea2fe85ffef49caf38bc270624d6","imagePullPolicy":"IfNotPresent","name":"k8s-centos-phpfpm-nginx-lumen","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2018-09-05T05:22:33Z","lastUpdateTime":"2018-09-05T05:22:33Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2018-09-05T05:20:01Z","lastUpdateTime":"2018-09-05T10:55:08Z","message":"ReplicaSet \"k8s-lumen-7f4674879\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":8,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: 2018-09-05T05:20:01Z
  generation: 11
  labels:
    app: k8s-lumen
  name: k8s-lumen
  namespace: default
  resourceVersion: "1895540"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/k8s-lumen
  uid: 56a07e26-b0cb-11e8-b231-42010a9400c2
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-lumen
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-lumen
    spec:
      containers:
      - image: gcr.io/rebatemango-dev/k8s-centos-phpfpm-nginx-lumen:06723594668379754a587b66f6210bfd69fb68f7
        imagePullPolicy: IfNotPresent
        name: k8s-centos-phpfpm-nginx-lumen
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2018-09-06T09:06:34Z
    lastUpdateTime: 2018-09-06T09:06:34Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-09-05T05:20:01Z
    lastUpdateTime: 2018-09-06T09:22:09Z
    message: ReplicaSet "k8s-lumen-6684dc66f7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
